name: linkedin_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.0.5
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  carousel_slider: ^4.0.0
  provider: ^6.0.2
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  google_sign_in: ^5.2.4
  github_sign_in: ^0.0.5-dev.4
  dio: ^4.0.4
  flutter_dotenv: ^5.0.2
  location: ^4.3.0
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  smart_reply: ^0.1.0
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/linkedin.png"

flutter_native_splash:
  color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/image/login-assets/
    - assets/config/
